app/models.py
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from app import login
from datetime import datetime
from . import db

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    email = db.Column(db.String(120), index=True, unique=True)
    password_hash = db.Column(db.String(128))
    posts = db.relationship('Post', backref='author', lazy='dynamic')

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return f'<User {self.username}>'

class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(64))
    body = db.Column(db.String(500))
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    comments = db.relationship('Comment', backref='post', lazy='dynamic')

    def __repr__(self):
        return f'<Post {self.id}>'

class Comment(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    body = db.Column(db.String(200))
    post_id = db.Column(db.Integer, db.ForeignKey('post.id'))

    def __repr__(self):
        return f'<Comment {self.id}>'

@login.user_loader
def load_user(id):
    return User.query.get(int(id))

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField, SelectField, TextAreaField
from wtforms.validators import ValidationError, DataRequired, Email, EqualTo
from wtforms import validators
from app.models import User

class AddForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired()])
    body = TextAreaField('Body', [validators.optional(), validators.length(max=1000)])
    submit = SubmitField('Submit')

class AddCommentForm(FlaskForm):
    body = TextAreaField('Comment', [validators.optional(), validators.length(max=1000)])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager
from flask_mail import Mail

db = SQLAlchemy()
migrate = Migrate()
login = LoginManager()
mail = Mail()


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)
    mail.init_app(app)

    db.init_app(app)
    migrate.init_app(app, db)
    login.init_app(app)

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    from app.auth import bp as auth_bp
    app.register_blueprint(auth_bp)

    return app

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes, forms

app/main/routes.py
from flask import render_template, redirect, url_for, flash
from flask_login import current_user, login_user, logout_user
from sqlalchemy import desc
import app
from app.main import bp
from app import db
import requests
from app.models import User, Post, Comment
from app.main import forms


@bp.route('/')
def index():
    # get the quote of the day
    url = "http://quotes.stormconsultancy.co.uk/random.json"
    response = requests.get(url).json()

    # get all the posts for displaying
    posts = Post.query.order_by(desc(Post.timestamp)).all()
    return render_template('index.html', posts=posts, User=User, quote=response)

@bp.route('/post/<post_id>', methods=['GET', 'POST'])
def post(post_id):
    post = Post.query.get(post_id)
    return render_template('post.html', post=post)

@bp.route('/add-post', methods=['GET', 'POST'])
def add_post():
    # go to login in page if user is not logged in
    if current_user.is_anonymous:
        return redirect(url_for('auth.login'))

    form = forms.AddForm()

    if form.validate_on_submit():
        post = Post(author=current_user, title=form.title.data, body=form.body.data)
        db.session.add(post)
        db.session.commit()
        return redirect(url_for('main.index'))

    return render_template('add_post.html', form=form)

@bp.route('/user/<user>')
def user(user):
    # go to login in page if user is not logged in
    if current_user.is_anonymous:
        return redirect(url_for('auth.login'))
    
    user = User.query.filter_by(username=user).first()
    pitches = pitches.query.filter_by(author=user).all()
    return render_template('user.html', user=user, pitches=pitches)

@bp.route('/comments/<post>')
def comments(post):
    comments = Comment.query.filter_by(post=Post.query.get(post)).all()
    return render_template('comments.html', post=Post.query.get(post), comments=comments)

@bp.route('/add-comment/<post>', methods=['GET', 'POST'])
def add_comment(post):
    # go to login in page if user is not logged in
    if current_user.is_anonymous:
        return redirect(url_for('auth.login'))

    form = forms.AddCommentForm()

    if form.validate_on_submit():
        comment = Comment(post=Post.query.get(post), body=form.body.data)
        db.session.add(comment)
        db.session.commit()
        return redirect(url_for('main.comments', post=post))

    return render_template('add_comment.html', form=form)

app/templates/add_comment.html
{% extends 'base.html' %}

{% block content %}
    <div class="login-container settings-container ">
        <h1 class="form-title">Add A New Comment</h1>
        <form class="add-form" action="" method="post">
            {{ form.hidden_tag() }}
            <p>
                {{ form.body(cols=100, rows=20) }}<br>
                {% for error in form.body.errors %}
                <span class="required-field">{{ error }}</span>
                {% endfor %}
            </p>
            <p>{{ form.submit() }}</p>
        </form>
    </div>
{% endblock %}

app/templates/add_post.html
{% extends 'base.html' %}

{% block content %}
    <div class="login-container settings-container ">
        <h1 class="form-title">Add Post</h1>
        <form class="add-form" action="" method="post">
            {{ form.hidden_tag() }}
            <p>
                {{ form.title.label }}<br>
                {{ form.title(size=32) }}<br>
                {% for error in form.title.errors %}
                <span class="required-field">{{ error }}</span>
                {% endfor %}
            </p>
            <p>
                {{ form.body.label }}<br>
                {{ form.body(cols=100, rows=20) }}<br>
                {% for error in form.body.errors %}
                <span class="required-field">{{ error }}</span>
                {% endfor %}
            </p>
            <p>{{ form.submit() }}</p>
        </form>
    </div>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blogger</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
    {# navigation bar #}
    <nav>
        <a class="nav-title" href="{{ url_for('main.index') }}">Blogger</h1>
        {% if current_user.is_authenticated %}
        <div class="links nav-large-links">
        {% else  %}
        <div class="links nav-small-links">
        {% endif %}
            {% if current_user.is_anonymous %}
            <a href="{{ url_for('auth.login') }}">Log In</a>
            {% else %}
            <a href="{{ url_for('auth.logout') }}">Log Out</a>
            {% endif %}
            <a href="{{ url_for('auth.signup') }}">Sign Up</a>
        </div>
    </nav>
    {# flashed messages #}
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <ul>
        {% for message in messages %}
            <li class="flashed-message">{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    {% endwith%}

    {# content block  #}
    {% block content %}{% endblock %}
</body>
</html>

app/templates/comments.html
{% extends "base.html" %}

{% block content%}
    <div class="comments-container">
        <div class="title">
            <h1>{{ post.title.title() }} Comments</h1>
            <a class="add-button comments-btn" href="{{ url_for("main.add_comment", post=post.id) }}">Add Comment</a>
        </div>
        <div class="comments">
            {% if comments %}
                {% for comment in comments %}
                    <div class="post post-margin">
                        <h1>{{ comment.body }}</h1>
                        <h2>{{ post.author.username.title() }}</h2>
                    </div>
                {% endfor %}
            {% else %}
                <h4>There are no comments for this post.</h4>
            {% endif %}
        </div>
    </div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block content %}
    {# hero  #}
    <div class="hero">
        {% if quote %}
        <div class="hero-text">
            <p id="quote-indicator">Today's Quote</p>
            <h1>"{{ quote.quote }}"</h1>
            <p id="subtitle">Please read through below to see what's going on in our community</p>
        </div>
        {% else %}
        <div class="hero-text">
            <h1>Understanding our community</h1>
            <p>New posts</p>
        </div>
        {% endif %}
    </div>

    <div class="posts">
        <div class="hero">
            <h1>Posts</h1>
            <a class="add-button" href="{{ url_for("main.add_post") }}">Add Post</a>
        </div>
        {% if posts %}
            {% for post in posts %}
                <div class="post">
                    <h1>{{ post.title }}</h1>
                    <h2>Author: {{ User.query.get(post.user_id).username }}</h2>
                    <h2>Date Posted: {{ post.timestamp.date().day }}/{{ post.timestamp.date().month}}/{{ post.timestamp.date().year}}</h2>
                    <a href="{{ url_for('main.post', post_id=post.id) }}">Read More...</a>
                </div>
            {% endfor %}
        {% else %}
            <h1 class="no-posts">0 posts</h1>
        {% endif %}
    </div>
{% endblock %}

app/templates/post.html
{% extends 'base.html' %}

{% block content %}
    <div class="post-grid">
        <h1 class="post-title">{{ post.title.title() }}</h1>
        <h2 class="post-author">By: {{ post.author.username.title() }}</h2>
        <p class="post-body">{{ post.body }}</p>
        <a class="post-comments" href="{{ url_for('main.comments', post=post.id)}}" class="comments">See Comments</a>
    </div>
{% endblock %}